# Generated by Django 3.1.12 on 2025-03-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lic_app', '0002_agentprofile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Agent'), (3, 'User')]),
        ),
    ]
