# Generated by Django 3.1.12 on 2025-03-10 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lic_app', '0004_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('Health', 'Health Insurance'), ('Life', 'Life Insurance'), ('Vehicle', 'Vehicle Insurance'), ('Property', 'Property Insurance')], max_length=20)),
                ('description', models.TextField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
