# Generated by Django 3.1.12 on 2025-03-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lic_app', '0005_insurancepolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
