# Generated by Django 3.1.12 on 2025-03-27 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lic_app', '0007_purchasedpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHead_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polcy_name', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_head_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubHead_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polcy_name', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_head_policies', to=settings.AUTH_USER_MODEL)),
                ('head_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_policies', to='lic_app.mainhead_policy')),
            ],
        ),
        migrations.CreateModel(
            name='SubHead_Policy_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=50)),
                ('uin_no', models.CharField(max_length=50)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='policy_pdfs/')),
                ('sub_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='lic_app.subhead_policy')),
            ],
        ),
    ]
