# Generated by Django 3.1.12 on 2025-03-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lic_app', '0008_mainhead_policy_subhead_policy_subhead_policy_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_years', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='lic_app.subhead_policy')),
            ],
        ),
    ]
