# Generated by Django 3.1.12 on 2025-03-29 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lic_app', '0011_insuranceclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_InsuranceClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=50)),
                ('uin_no', models.CharField(max_length=50)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('bank_details', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='lic_app.userpolicypurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceClaim',
        ),
    ]
